/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

import java.awt.Toolkit;

/**
 *
 * @author Danya
 */
public class F_Menu extends javax.swing.JFrame {

    private main parent = null;
    private F_Withdraw f_Withdraw = null;
    private F_Equity f_equity = null;
    private F_Story f_story = null;
    private F_Pay f_pay  = null;
    
    /**
     * Creates new form F_Menu
     */
    public F_Menu(main parent) {
        this.parent = parent;
        initComponents();
        additionalinit();
    }

    private void additionalinit(){
        //центрирование окна
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width-this.getWidth())/2, (Toolkit.getDefaultToolkit().getScreenSize().height-this.getHeight())/2);
        f_Withdraw = new F_Withdraw(this);
        f_equity = new F_Equity(this);
        f_story = new F_Story(this);
        f_pay = new F_Pay(this);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_menu = new javax.swing.JPanel();
        B_withdraw = new javax.swing.JButton();
        L_withdraw = new javax.swing.JLabel();
        B_balance = new javax.swing.JButton();
        L_balance = new javax.swing.JLabel();
        L_Story = new javax.swing.JLabel();
        B_Story = new javax.swing.JButton();
        B_pay = new javax.swing.JButton();
        L_pay = new javax.swing.JLabel();
        B_cancel = new javax.swing.JButton();
        L_cancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Меню");
        setName("F_Menu"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 330));
        setResizable(false);

        P_menu.setBackground(new java.awt.Color(215, 214, 214));
        P_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        B_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_withdrawActionPerformed(evt);
            }
        });

        L_withdraw.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_withdraw.setText("Снятие наличных");

        B_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_balanceActionPerformed(evt);
            }
        });

        L_balance.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_balance.setText("Остаток на счету");

        L_Story.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_Story.setText("Выписка");

        B_Story.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_StoryActionPerformed(evt);
            }
        });

        B_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_payActionPerformed(evt);
            }
        });

        L_pay.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_pay.setText("Оплата услуг");

        B_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cancelActionPerformed(evt);
            }
        });

        L_cancel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_cancel.setText("Отмена");

        javax.swing.GroupLayout P_menuLayout = new javax.swing.GroupLayout(P_menu);
        P_menu.setLayout(P_menuLayout);
        P_menuLayout.setHorizontalGroup(
            P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(B_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(L_cancel)
                .addGap(52, 52, 52)
                .addGroup(P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_menuLayout.createSequentialGroup()
                        .addComponent(L_pay)
                        .addGap(43, 43, 43))
                    .addComponent(L_balance)
                    .addComponent(L_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_Story))
                .addGroup(P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Story, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        P_menuLayout.setVerticalGroup(
            P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_menuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_withdraw))
                .addGap(40, 40, 40)
                .addGroup(P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_balance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_balance))
                .addGap(40, 40, 40)
                .addGroup(P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_Story)
                    .addGroup(P_menuLayout.createSequentialGroup()
                        .addComponent(B_Story, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(B_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(L_cancel)
                                .addComponent(L_pay))
                            .addComponent(B_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cancelActionPerformed
        parent.setVisible(true);
        parent.clear();
        this.setVisible(false);
    }//GEN-LAST:event_B_cancelActionPerformed

    private void B_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_withdrawActionPerformed
        // TODO add your handling code here:
        f_Withdraw.clear();
        f_Withdraw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_B_withdrawActionPerformed

    private void B_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_balanceActionPerformed
        this.setVisible(false);
        f_equity.setVisible(true);
    }//GEN-LAST:event_B_balanceActionPerformed

    private void B_StoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_StoryActionPerformed
        this.setVisible(false);
        f_story.setVisible(true);
    }//GEN-LAST:event_B_StoryActionPerformed

    private void B_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_payActionPerformed
        this.setVisible(false);
        f_pay.setVisible(true);
    }//GEN-LAST:event_B_payActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Story;
    private javax.swing.JButton B_balance;
    private javax.swing.JButton B_cancel;
    private javax.swing.JButton B_pay;
    private javax.swing.JButton B_withdraw;
    private javax.swing.JLabel L_Story;
    private javax.swing.JLabel L_balance;
    private javax.swing.JLabel L_cancel;
    private javax.swing.JLabel L_pay;
    private javax.swing.JLabel L_withdraw;
    private javax.swing.JPanel P_menu;
    // End of variables declaration//GEN-END:variables
}
