/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Danya
 */
public class F_Pay extends javax.swing.JFrame {
    
    private static final int SService = 0;
    private static final int SPhone = 1;
    private static final int SEnergy = 2;
    private static final int STax = 3;
    private static final int SFine = 4;
    
    private int selected_service = -1;

    private F_Menu parent = null;
    /**
     * Creates new form F_Pay
     */
    public F_Pay(F_Menu parent) {
        this.parent = parent;
        initComponents();
        additionalinit();
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); 
        f_no.setVisible(false);
        B_ok.setVisible(false);
        L_ok.setVisible(false);
        L_SUMM.setVisible(false);
        selected_service = -1;
    }
    
    private void setService(int service){
        switch (service) {
            case SService: showService("Введите номер квитанции"); break;
            case SPhone: showService("Введите номер телефона"); break;
            case STax: showService("Введите ИНН"); break;
            case SFine: showService("Введите номер квитанции"); break;
            case SEnergy: showService("Введите номер квитанции"); break;
            default: return;
        }
        selected_service = service;
    }
    
    private void showService(String name){
        f_no.setVisible(true);
        B_ok.setVisible(true);
        L_ok.setVisible(true);
        f_no.setText(name);
        L_SUMM.setText("Сумма");
        L_SUMM.setVisible(true);
    }
    
    private void additionalinit(){
        //центрирование окна
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width-this.getWidth())/2, (Toolkit.getDefaultToolkit().getScreenSize().height-this.getHeight())/2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_pay = new javax.swing.JPanel();
        B_energy = new javax.swing.JButton();
        L_Energy = new javax.swing.JLabel();
        B_service = new javax.swing.JButton();
        L_service = new javax.swing.JLabel();
        B_fine = new javax.swing.JButton();
        L_fine = new javax.swing.JLabel();
        B_phone = new javax.swing.JButton();
        L_phone = new javax.swing.JLabel();
        B_back = new javax.swing.JButton();
        L_back = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        B_tax = new javax.swing.JButton();
        L_tax = new javax.swing.JLabel();
        f_no = new javax.swing.JTextField();
        B_ok = new javax.swing.JButton();
        L_ok = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 35), new java.awt.Dimension(0, 35), new java.awt.Dimension(32767, 35));
        L_SUMM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Оплата");
        setName("f_pay"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        P_pay.setBackground(new java.awt.Color(215, 214, 214));
        P_pay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        B_energy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_energyActionPerformed(evt);
            }
        });

        L_Energy.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_Energy.setText("Электроэнергия");

        B_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_serviceActionPerformed(evt);
            }
        });

        L_service.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_service.setText("Комм. услуги");

        B_fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_fineActionPerformed(evt);
            }
        });

        L_fine.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_fine.setText("Штрафы");

        B_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_phoneActionPerformed(evt);
            }
        });

        L_phone.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_phone.setText("Телефон");

        B_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_backActionPerformed(evt);
            }
        });

        L_back.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_back.setText("Назад");

        B_tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_taxActionPerformed(evt);
            }
        });

        L_tax.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_tax.setText("Налоги");

        f_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_noMouseClicked(evt);
            }
        });

        B_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_okActionPerformed(evt);
            }
        });

        L_ok.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_ok.setText("Подтвердить");

        L_SUMM.setText("Сумма");
        L_SUMM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L_SUMMMouseClicked(evt);
            }
        });
        L_SUMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_SUMMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_payLayout = new javax.swing.GroupLayout(P_pay);
        P_pay.setLayout(P_payLayout);
        P_payLayout.setHorizontalGroup(
            P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_payLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P_payLayout.createSequentialGroup()
                        .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_energy, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_Energy)
                            .addComponent(L_tax)
                            .addComponent(jLabel6)
                            .addComponent(L_back)))
                    .addComponent(f_no)
                    .addComponent(L_SUMM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L_fine)
                        .addComponent(L_service)
                        .addGroup(P_payLayout.createSequentialGroup()
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(L_ok)))
                    .addGroup(P_payLayout.createSequentialGroup()
                        .addComponent(L_phone)
                        .addGap(38, 38, 38)))
                .addGap(33, 33, 33)
                .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B_service, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_fine, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        P_payLayout.setVerticalGroup(
            P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_payLayout.createSequentialGroup()
                .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_payLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_ok)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P_payLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(f_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(L_SUMM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(B_service, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L_service)
                        .addComponent(L_Energy))
                    .addComponent(B_energy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(B_fine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_payLayout.createSequentialGroup()
                        .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_tax)
                            .addComponent(L_fine))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(B_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_payLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_phone)
                        .addComponent(B_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L_back)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_noMouseClicked
        f_no.setText("");
    }//GEN-LAST:event_f_noMouseClicked

    private void B_taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_taxActionPerformed
        setService(STax);
    }//GEN-LAST:event_B_taxActionPerformed

    private void B_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_backActionPerformed
        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_B_backActionPerformed

    private void B_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_phoneActionPerformed
        setService(SPhone);
    }//GEN-LAST:event_B_phoneActionPerformed

    private void B_fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_fineActionPerformed
        setService(SFine);
    }//GEN-LAST:event_B_fineActionPerformed

    private void B_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_serviceActionPerformed
        setService(SService);
    }//GEN-LAST:event_B_serviceActionPerformed

    private void B_energyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_energyActionPerformed
        setService(SEnergy);
    }//GEN-LAST:event_B_energyActionPerformed

    private void L_SUMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_SUMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_SUMMActionPerformed

    private void L_SUMMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L_SUMMMouseClicked
        L_SUMM.setText("");
    }//GEN-LAST:event_L_SUMMMouseClicked

    private void B_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_okActionPerformed
        float amount=0;
        try {
            amount = Float.parseFloat(L_SUMM.getText());
            if(amount<=0)
                throw new NumberFormatException ();
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Пожалуйста, введите число.");
            L_SUMM.setText("");
        }
        float commision = DataBase.getInstance().moneyTransfer(selected_service, amount, f_no.getText());
        if (commision>=0) JOptionPane.showMessageDialog(this, "Операция прошла успешно. Коммисия составила: "+commision);
        else
            JOptionPane.showMessageDialog(this, "Операция не проведена");
    }//GEN-LAST:event_B_okActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_back;
    private javax.swing.JButton B_energy;
    private javax.swing.JButton B_fine;
    private javax.swing.JButton B_ok;
    private javax.swing.JButton B_phone;
    private javax.swing.JButton B_service;
    private javax.swing.JButton B_tax;
    private javax.swing.JLabel L_Energy;
    private javax.swing.JTextField L_SUMM;
    private javax.swing.JLabel L_back;
    private javax.swing.JLabel L_fine;
    private javax.swing.JLabel L_ok;
    private javax.swing.JLabel L_phone;
    private javax.swing.JLabel L_service;
    private javax.swing.JLabel L_tax;
    private javax.swing.JPanel P_pay;
    private javax.swing.JTextField f_no;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
