/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

import java.awt.Toolkit;
import java.text.ParseException;
import javax.swing.text.MaskFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author llama
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        additionalinit();
    }

    private void additionalinit(){
        //центрирование окна
        this.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width-this.getWidth())/2, (Toolkit.getDefaultToolkit().getScreenSize().height-this.getHeight())/2);
        f_menu = new F_Menu(this);
        DataBase.getInstance();
    }
    
    
    public void clear(){
        f_card_no.setText("");
        f_pin_code.setText("");
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_hello = new javax.swing.JPanel();
        f_pin_code = new javax.swing.JPasswordField();
        MaskFormatter formatter = null;
        try {
            formatter = new MaskFormatter("#########");
        } catch (ParseException e) {}
        f_card_no = new javax.swing.JFormattedTextField(formatter);
        b_clear = new javax.swing.JButton();
        L_pin_code = new javax.swing.JLabel();
        L_Hello = new javax.swing.JLabel();
        b_ok = new javax.swing.JButton();
        L_Card_No = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Банкомат");
        setBackground(new java.awt.Color(51, 204, 0));
        setUndecorated(true);
        setResizable(false);

        P_hello.setBackground(new java.awt.Color(215, 214, 214));
        P_hello.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        f_pin_code.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        f_card_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        b_clear.setText("Сброс");
        b_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearActionPerformed(evt);
            }
        });

        L_pin_code.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_pin_code.setText("Пин код:");

        L_Hello.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_Hello.setText("Пожалуйста, введите данные:");

        b_ok.setText("Ввод");
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        L_Card_No.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        L_Card_No.setText("Номер карточки:");

        javax.swing.GroupLayout P_helloLayout = new javax.swing.GroupLayout(P_hello);
        P_hello.setLayout(P_helloLayout);
        P_helloLayout.setHorizontalGroup(
            P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_helloLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_helloLayout.createSequentialGroup()
                        .addGroup(P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(L_Card_No, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(L_pin_code, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f_pin_code)
                            .addComponent(b_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(f_card_no, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P_helloLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(L_Hello)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        P_helloLayout.setVerticalGroup(
            P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_helloLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(L_Hello)
                .addGap(45, 45, 45)
                .addGroup(P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Card_No)
                    .addComponent(f_card_no, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_pin_code)
                    .addComponent(f_pin_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(P_helloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_hello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_hello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        DataBase.getInstance().setLogin(f_card_no.getText(), f_pin_code.getText());
        if (DataBase.getInstance().checkPasswd()) {
            f_menu.setVisible(true);
            this.setVisible(false);   
        }
        else JOptionPane.showMessageDialog(this, "Неверный pin или номер!");
    }//GEN-LAST:event_b_okActionPerformed

    private void b_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearActionPerformed
        this.clear();
    }//GEN-LAST:event_b_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_Card_No;
    private javax.swing.JLabel L_Hello;
    private javax.swing.JLabel L_pin_code;
    private javax.swing.JPanel P_hello;
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_ok;
    private javax.swing.JFormattedTextField f_card_no;
    private javax.swing.JPasswordField f_pin_code;
    // End of variables declaration//GEN-END:variables
    // Элеметны добавленные вручную
    JFrame f_menu = null;
}
